# Generated by Django 5.2.7 on 2025-10-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industria', models.CharField(max_length=100)),
                ('trabajadores', models.IntegerField()),
                ('prioridad', models.CharField(max_length=100)),
                ('email_asociado', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('rubro', models.CharField(max_length=100)),
                ('tamaño', models.CharField(max_length=50)),
                ('identificador', models.CharField(max_length=20)),
                ('email_asociado', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('area_empresa', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('presupuesto', models.IntegerField()),
            ],
        ),
    ]
