# Generated by Django 5.2.7 on 2025-10-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Tema', models.CharField(max_length=100)),
                ('area_empresa', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('presupuesto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadorEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Rut', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='empresas',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
