<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria_app', '0002_proyecto_trabajadorempresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industria', models.CharField(max_length=100)),
                ('trabajadores', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('prioridad', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TrabajadorEmpresa',
        ),
    ]
=======
# Generated by Django 5.2.7 on 2025-10-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria_app', '0002_proyecto_trabajadorempresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industria', models.CharField(max_length=100)),
                ('trabajadores', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('prioridad', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TrabajadorEmpresa',
        ),
    ]
>>>>>>> 88f5804 (carga inicial)
