# Generated by Django 5.2.7 on 2025-10-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria_app', '0003_diagnosticorapido_delete_trabajadorempresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticorapido',
            old_name='email',
            new_name='email_asociado',
        ),
    ]
