# Generated by Django 5.2.7 on 2025-10-21 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria_app', '0004_rename_email_diagnosticorapido_email_asociado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='Tema',
            new_name='tema',
        ),
    ]
